### ISSUE TITLE
[Warning] SSPanelPlugin: json: cannot unmarshal string into Go struct field NodeinfoResponse.data of type model.NodeInfo

### ISSUE THREAD

**Issue by messi06** [pandoraes/V2Ray-With-SSpanel#1]
[Warning] SSPanelPlugin: json: cannot unmarshal string into Go struct field NodeinfoResponse.data of type model.NodeInfo

any idea what should i do please ?

**Comment by pandoraes** [comment]
Check / etc / v2ray/ config.json
